name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v2.1.0

      - name: Run ShellCheck
        run: scripts/shellcheck.bash

      - name: Run shfmt
        run: scripts/shfmt.bash

  integration-test:
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test integration with asdf
        uses: asdf-vm/actions/plugin-test@v2.1.0
        with:
          command: maestro --version
